### ISSUE TITLE
Show total rows in report

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/agile-visitors#40]
**Is your feature request related to a problem? Please describe.**
Show the total row returned by server. Feel free to put it in logic area, like table footer, header...

![image](https://user-images.githubusercontent.com/35310226/94878838-92a08e80-042c-11eb-8fe5-6abf921810d5.png)

**Describe the solution you'd like**
Count the server returned response.

**Describe alternatives you've considered**
Use the pagination object include in server response.

**Additional context**
NONE

**Comment by TobyAsE** [comment]
I'd like to try this
