### ISSUE TITLE
Set maximum characters for fields in the visit registration form

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/agile-visitors#44]
**Is your feature request related to a problem? Please describe.**
Set max length in form fields.

**Describe the solution you'd like**

Code Visitor and Receiver: **30**
For a full name Visitor and Receiver: **70**
Title/Position: **150**
Reason for visit: **256**

:warning: If you consider that any of the fields should be lower or higher, please let me know in a comment before applying anything outside of these instructions.

Helps links: [What is a reasonable length limit on person “Name” fields?
](https://stackoverflow.com/q/30485/8009061)

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by sandy9808** [comment]
Hi there, i would like to work on this issue.

**Comment by Jadhielv** [comment]
LGTM  @itsalb3rt
