### ISSUE TITLE
Enhance UX for fields in visit form (Maximum length)

### ISSUE THREAD

**Issue by Jadhielv** [itsalb3rt/agile-visitors#48]
**Is your feature request related to a problem? Please describe.**

Enhance UX for fields in visit form (prop **maxlength**), when exceeded limit show the following **message**:

Please use maximum `val => val.length` characters.

**Describe the solution you'd like**
Apply enhancement according to what was discussed.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by itsalb3rt** [comment]
WIP
