### ISSUE TITLE
Add language switcher

### ISSUE THREAD

**Issue by Jadhielv** [itsalb3rt/agile-visitors#49]
**Is your feature request related to a problem? Please describe.**
Create language switcher using `q-btn`, `q-select` or whatever you prefer. 

**Describe the solution you'd like**
Use **i18n** from **Quasar**, tab [Create-language-switcher](https://quasar.dev/options/app-internationalization#Create-language-switcher)

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by lewandy** [comment]
Nice!, I will work on this.
