### ISSUE TITLE
Enhance UX for translate labels and fix spelling errors

### ISSUE THREAD

**Issue by Jadhielv** [itsalb3rt/agile-visitors#51]
**Is your feature request related to a problem? Please describe.**

- **Index**

![imagen](https://user-images.githubusercontent.com/24376900/95003540-509f5600-05ae-11eb-973c-fc28d85cd13a.png)

`Código empleado`
`Nombre completo`

![imagen](https://user-images.githubusercontent.com/24376900/95003608-f4890180-05ae-11eb-9ddd-2eaabe1dae4e.png)

`Español`

- **Reports**

![imagen](https://user-images.githubusercontent.com/24376900/95003618-12566680-05af-11eb-83c4-e4920caf1b1d.png)

`CONSULTAR REPORTE`

![imagen](https://user-images.githubusercontent.com/24376900/95003651-2f8b3500-05af-11eb-951c-fc2f2143dd53.png)

`Código empleado`

![imagen](https://user-images.githubusercontent.com/24376900/95003680-72e5a380-05af-11eb-92ff-0976741beb39.png)

`Tengo 10 resultados`

![imagen](https://user-images.githubusercontent.com/24376900/95003700-9b6d9d80-05af-11eb-8150-2bcb5a558ccd.png)

`Registros`

![imagen](https://user-images.githubusercontent.com/24376900/95003706-b17b5e00-05af-11eb-95fc-cadb608db1e1.png)

Translate all labels of table

**Describe the solution you'd like**
Apply enhancement according to what was discussed.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by itsalb3rt** [comment]
One important thing, change "código empleado" for "código recepcionista"
