### ISSUE TITLE
Update demo image on README

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/agile-visitors#54]
**Is your feature request related to a problem? Please describe.**

A lot of changes have been made since the screenshot of the demo image was taken, I invite you to get creative and create an amazing image for the demo and place it in the README.

**Describe the solution you'd like**
Go to [https://agile-visitors.netlify.app/](https://agile-visitors.netlify.app/) and take some screenshots, the only requirement is that the demo image is ONE.

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by pushpak1300** [comment]
![Screenshot from 2020-10-05 09-10-34](https://user-images.githubusercontent.com/31663512/95038014-b09b1700-06ea-11eb-987f-89fb5661c5bb.png)
![Screenshot from 2020-10-05 09-10-23](https://user-images.githubusercontent.com/31663512/95038019-b4c73480-06ea-11eb-917c-410fe3dd6843.png)

I will make a collage of these two images and add it on a homepage.
