### ISSUE TITLE
Sanitize input fields

### ISSUE THREAD

**Issue by itsalb3rt** [itsalb3rt/agile-visitors#8]
**visits form**

- Create rule for all "code" inputs, accept only a-z, A-Z, -_#, no space or any other character.
- Name only accept a-z. A-Z and white space between characters
- Validate on the fly

Use rules [https://quasar.dev/vue-components/input#Internal-validation](https://quasar.dev/vue-components/input#Internal-validation)

**Comment by Jadhielv** [comment]
@itsalb3rt considering convenient to create another rule to limit `Title / Position` and `Reason for visit` fields. If you have time please take a look.

**Comment by itsalb3rt** [comment]
> @itsalb3rt considering convenient to create another rule to limit `Title / Position` and `Reason for visit` fields. If you have time please take a look.

Perfect, I'm going to create a new issus. It would be necessary to evaluate how many characters would be the maximum.
